## 1. NumPy Array basics with DataCamp

Have a look at the following DataCamp exercises, or, if you want to put in some more time, go through the [whole DataCamp chapter](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=1)

**1.1.** [Your First NumPy Array](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=2)

**1.2.** [Baseball players' height](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=3)

**1.3.** [Baseball player's BMI](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=4)

**1.4.** [Lightweight baseball players](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=5)

**1.5.** [Subsetting NumPy Arrays](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=7)

**1.6.** [Your First 2D NumPy Array](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=9)

**1.7.** [Baseball data in 2D form](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=10)

**1.8.** [Subsetting 2D NumPy Arrays](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=11)

**1.9.** [2D Arithmetic](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=12)

## 2. Functional array creation and manipulation

Make use of `numpy.array` to create an array `a` and stepwise produce the output listed below. Try not to create `a` explicitely, but try to use `numpy`-functions:
1. `print(a)` yields the following output:
```
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 2. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
```
*optional:* create the above array in one line, without using `;` (some research might be required).
2. Manipulate `a` such that `print(a)` yields the following output:
```
[[0. 0. 0. 0. 0.]
 [0. 3. 3. 3. 0.]
 [0. 3. 6. 3. 0.]
 [0. 3. 3. 3. 0.]
 [0. 0. 0. 0. 0.]]
```
3. Manipulate `a` further such that `print(a)` yields the following output:
```
[[0. 0. 0. 0. 0.]
 [0. 4. 3. 3. 0.]
 [0. 3. 8. 3. 0.]
 [0. 3. 3. 6. 0.]
 [0. 0. 0. 0. 4.]]
```
4. Manipulate `a` further such that `print(a)` yields the following output:
```
[[ 0.  0.  0.  0.  0.]
 [ 0.  4. -3. -3.  0.]
 [ 0.  3. -8. -3.  0.]
 [ 0.  3.  3.  6.  0.]
 [ 0.  0.  0.  0.  4.]]
```
5. Manipulate `a` further such that `print(a)` yields the following output:
```
[[ 0.  0.  0.  0.  0.]
 [ 0.  4.  3.  3.  0.]
 [ 0. -3. -8.  3.  0.]
 [ 0. -3. -3.  6.  0.]
 [ 0.  0.  0.  0.  4.]]
```

In [1]:
import numpy as np

a = np.zeros((5, 5))
a[1:-1, 1:-1] = 1
a[2:-2, 2:-2] = 2
print(a)

# optional: one-line creation, using np.outer() and '+'
b = np.outer(np.array([0, 1., 1, 1, 0]), np.array([0, 1, 1, 1, 0])) + np.outer(np.array([0, 0, 1., 0, 0]), np.array([0, 0, 1, 0, 0]))
print(b)

a = 3 * a
print(a)

d = np.diag([0, 1, 2, 3, 4])
a = a + d
print(a)

a[1:3, 2:4] = a[1:3, 2:4] * -1
print(a)

a = a.T
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 2. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 2. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 3. 3. 3. 0.]
 [0. 3. 6. 3. 0.]
 [0. 3. 3. 3. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 4. 3. 3. 0.]
 [0. 3. 8. 3. 0.]
 [0. 3. 3. 6. 0.]
 [0. 0. 0. 0. 4.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  4. -3. -3.  0.]
 [ 0.  3. -8. -3.  0.]
 [ 0.  3.  3.  6.  0.]
 [ 0.  0.  0.  0.  4.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  4.  3.  3.  0.]
 [ 0. -3. -8.  3.  0.]
 [ 0. -3. -3.  6.  0.]
 [ 0.  0.  0.  0.  4.]]


## 3. Fancy filtering

Assume you have an array `f` that represents some timeseries of oscillating values. 
1. For now `f` oscillates around some offset which can be estimated by its mean value. Normalize all values in `f` by subtracting its mean value.
2. Use a loop-approach to filter `f`. Set all values that are lesser than `-0.25` to `-0.25` (after normalizing `f`).
3. Use fancy indexing to filter `f` and repeat (2.)

Your result should yield the following output:
```
[ 0.35  0.85 -0.25  0.75 -0.05 -0.25 -0.25 -0.25  0.25  0.85 -0.25 -0.05]
```

In [2]:
import numpy as np

f = np.array([2.4, 2.9, 1.7, 2.8, 2.0, 1.4, 1.3, 1.7, 2.3, 2.9, 1.2, 2.0])
print(f)

f = f - f.mean()
print(f)

# 2.
f_filt_1 = np.empty(f.shape)
for i, elm in enumerate(f):
    if elm < -0.25:
        elm = -0.25
    f_filt_1[i] = elm
print(f_filt_1)

# 3.
f_filt_2 = f.copy()
f_filt_2[f_filt_2 < -0.25] = -0.25
print(f_filt_2)

[2.4 2.9 1.7 2.8 2.  1.4 1.3 1.7 2.3 2.9 1.2 2. ]
[ 0.35  0.85 -0.35  0.75 -0.05 -0.65 -0.75 -0.35  0.25  0.85 -0.85 -0.05]
[ 0.35  0.85 -0.25  0.75 -0.05 -0.25 -0.25 -0.25  0.25  0.85 -0.25 -0.05]
[ 0.35  0.85 -0.25  0.75 -0.05 -0.25 -0.25 -0.25  0.25  0.85 -0.25 -0.05]


## 4. Broadcasting the right way

Using the operation `arr // div`, with `arr` and `div` as defined below will broadcast `div` such that each *row* of `arr` is (integer-)divided by `div`. Find a way (using broadcasting) to (integer-)divide each *column* of `arr` is divided by `div`.

Your output should look like this:
```
[[0. 1. 2. 3. 4.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
```

In [3]:
import numpy as np

arr = np.arange(25).reshape(5, 5)
print(arr.shape)

div = np.array([1., 5, 10, 15, 20])
print(div.shape)

arr // div

(5, 5)
(5,)


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 5.,  1.,  0.,  0.,  0.],
       [10.,  2.,  1.,  0.,  0.],
       [15.,  3.,  1.,  1.,  0.],
       [20.,  4.,  2.,  1.,  1.]])

In [4]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
div

array([ 1.,  5., 10., 15., 20.])

In [6]:
div[:, np.newaxis]

array([[ 1.],
       [ 5.],
       [10.],
       [15.],
       [20.]])

In [7]:
print(arr.shape)
print(div[:, np.newaxis].shape)
arr // div[:, np.newaxis]

(5, 5)
(5, 1)


array([[0., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])