## `numpy`, what is it for?

Highly performant tool for numerical computations in python. Some initial points:
- many high-level number objects, that are implemented close to hardware
- flexible and convenient containers (*arrays*)
- easily handable multi-dimensional arrays
- *array oriented computing*

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

### Why use numpy-arrays? Why not built-in lists?

1. Mathematical intiuitive operations

In [2]:
l = [0, 1, 2, 3]
a = np.array([0, 1, 2, 3])

print(a, l, sep='\n')

[0 1 2 3]
[0, 1, 2, 3]


- Scalar operations:

In [3]:
print(a + 1)
print(a - 1)
print(2 * a)
print(a**2)
print(2**a)

[1 2 3 4]
[-1  0  1  2]
[0 2 4 6]
[0 1 4 9]
[1 2 4 8]


In [4]:
#print(l + 1)
#print(l - 1)
print(2 * l)
#print(l**2)
#print(2**l)

[0, 1, 2, 3, 0, 1, 2, 3]


- array operations:

In [5]:
b = np.array([-2, -1, 1, 2])

print(a, b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[0 1 2 3] [-2 -1  1  2]
[-2  0  3  5]
[2 2 1 1]
[ 0 -1  2  6]
[-0.  -1.   2.   1.5]


In [6]:
m = [-2, -1, 1, 2]

print(l, m)
print(l + m)
#print(l - m)
#print(l * m)
#print(l / m)

[0, 1, 2, 3] [-2, -1, 1, 2]
[0, 1, 2, 3, -2, -1, 1, 2]


- many more to come

2. Performance

In [7]:
large_list = list(range(20))
large_array = np.array(large_list)

In [8]:
%timeit for i in large_list: i**2

3.34 µs ± 30.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
%timeit for i in large_array: i**2

5.77 µs ± 66.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
%timeit large_array**2

594 ns ± 4.43 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


As a large package, `numpy` offers many different objects and operations. You can easily find things using the following:

In [11]:
np.array?
np.lookfor('create array')
np.con*?

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a 

### Some basics: Manual and functional creation of arrays

In [12]:
# 1D:
print("Tests for manual creation of 1D arrays here:")
a_1d = np.array([0, 1, 2, 3])
print(a_1d)
print(a_1d.ndim)
print(a_1d.shape)
print(len(a_1d))

# 2D:
print("\nTests for manual creation of 2D arrays here:")
a_2d = np.array([[0, 1, 2], 
                [3, 4, 5]])
print(a_2d)
print(a_2d.ndim)
print(a_2d.shape)
print(len(a_2d))

# 3D:
print("\nTests for manual creation of 3D arrays here:")
a_3d = np.array([[[1, 2], 
                  [1, 2]], 
                 [[2, 3], 
                  [2, 3]]])
print(a_3d)
print(a_3d.ndim)
print(a_3d.shape)
print(len(a_3d))

Tests for manual creation of 1D arrays here:
[0 1 2 3]
1
(4,)
4

Tests for manual creation of 2D arrays here:
[[0 1 2]
 [3 4 5]]
2
(2, 3)
2

Tests for manual creation of 3D arrays here:
[[[1 2]
  [1 2]]

 [[2 3]
  [2 3]]]
3
(2, 2, 2)
2


In [13]:
# Simple range-like arrays
a = np.arange(10)
print(a)
b = np.arange(1, 9, 2)
print(b)

# Create a span, for example for x-axis
c = np.linspace(0, 1, 6)
print(c)
d = np.linspace(0, 1, 5, endpoint=False)
print(d)

# Other utilities
a = np.ones((3, 3))
print(a)
b = np.zeros((3, 3))
print(b)
c = np.empty((3, 3))  # quickest way for larger arrays
print(c)
d = np.eye(3)
print(d)
e = np.diag(np.array([1., 2., 3.]))
print(e)

# Random numbers with
a = np.random.rand(4)
print(a)
b = np.random.randn(4)
print(b)
np.random.seed(1234)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[0.01963363 0.34863486 0.53016406 0.63560301]
[-1.60090512  0.17130266 -1.61438401 -2.77030788]


### Different data types

In [14]:
a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1., 2., 3.])
print(b.dtype)

int64
float64


In [15]:
c = np.array([1, 2, 3], dtype=float)
print(c.dtype)

d = np.array([1., 2., 3.], dtype='int32')
print(d.dtype)

float64
int32


As with many other declarations in python, array-types are taken care of automatically

In [16]:
c1, c2, c3 = 1 + 1j, 1.1j, 0 + 6 * 10j
e = np.array([c1, c2, c3])
print(e.dtype)

f = np.array([True, False, False, True])
print(f.dtype)

g = np.array(['banana', 'apple', 'milk'])
print(g.dtype)

complex128
bool
<U6


### Indexing and slicing

Recall indexing and slicing using lists. arrays of course behave very similar.

In [17]:
a = np.arange(10)
print(a)
print(a[0], a[2], a[-1])
print(a[::-1])
print(a[:4])
print(a[1:3])
print(a[3:])

# combine slicing and assignment
a[5:] = 10.5
print(a)
b = np.arange(5)
print(b)
a[5:] = b
print(a)

[0 1 2 3 4 5 6 7 8 9]
0 2 9
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3]
[1 2]
[3 4 5 6 7 8 9]
[ 0  1  2  3  4 10 10 10 10 10]
[0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4]


In [18]:
a = np.diag(np.arange(3))
print(a)
print(a[1, 1])
a[2, 1] = 10  # third line, second column
print(a)  # in 2D, first rows, then columns
print(a[1])

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
[[ 0  0  0]
 [ 0  1  0]
 [ 0 10  2]]
[0 1 0]


### Fancy indexing

In [19]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


As array allow operations with standard operators, the following is possible:

In [20]:
for elm in arr:
    if elm % 3 == 0:
        print(elm, 'is divisible by 3: elm % 3 =', elm % 3)

30 is divisible by 3: elm % 3 = 0
60 is divisible by 3: elm % 3 = 0
90 is divisible by 3: elm % 3 = 0


In [21]:
mask = (arr % 3 == 0)
print(mask)
masked_arr = arr[mask]
print(masked_arr)

[False False  True False False  True False False  True False]
[30 60 90]


In [22]:
print(arr[arr % 3 == 0])

[30 60 90]


In [23]:
print(arr[arr < 65])

[10 20 30 40 50 60]


In [24]:
mask = [4, 7, 9]
print(arr[mask])

arr[mask] = -1
print(arr)

arr[[7, 1]] = 33
print(arr)

[ 50  80 100]
[10 20 30 40 -1 60 70 -1 90 -1]
[10 33 30 40 -1 60 70 33 90 -1]


### More basics: Methods and reductions

In [25]:
x = np.array([0, 2, 3, 5, 2])
print(x)

print(x.min())
print(x.max())

print(x.argmin())  # index of min
print(x.argmax())  # index of max

[0 2 3 5 2]
0
5
0
3


In [26]:
x = np.array([1, 2, 3, 4])
print(np.sum(x))
print(x.sum())

10
10


In [27]:
help(np.sum)
help(x.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [28]:
x = np.array([[1, 1, 1], 
             [2, 2, 2]])
print(x)
print(x.shape)
print(x.sum(axis=0))
print(x.sum(axis=0).shape)  # the first axis is reduced

print(x.sum(axis=1))
print(x.sum(axis=1).shape)  # the second axis is reduced

[[1 1 1]
 [2 2 2]]
(2, 3)
[3 3 3]
(3,)
[3 6]
(2,)


In [29]:
x = np.array([[1, 1, 1], 
             [2, 2, 2]])
print(x)
print(x.ravel())

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


Array comparison via `any` and `all`

In [30]:
a = np.array([0, 2, 3, 5, 2])
b = np.array([0, 2, 3, -1, 2])

print(np.any(a == b))  # are ANY entries EQUAL?
print(np.all(a == b))  # are ALL entries EQUAL?

print(np.all(a == a))

True
False
True


Some more methods for simple statistics

In [31]:
x = np.array([0, 2, 3, 5, 2])
y = np.array([[0, 1, 3], 
             [6, 9, 8]])

print(x.mean())
#print(x.median())
#np.lookfor('median')
print(np.median(x))
print(x.std())

print(y.shape)
print(y.mean(axis=1))  # the second axis is reduced (averaged)

2.4
2.0
1.624807680927192
(2, 3)
[1.33333333 7.66666667]


### Broadcasting

Often times data is given in multiple dimensions (example HMI-data: times-series of 2D images in multiple channels), but data manipulations is done in far less dimensions (example active regions masks: 2D masks or filters).

In [32]:
data = np.ones((3, 3, 10))
print(data.shape)
print(data[..., -1])

mask = np.ones((3, 3))
mask[1, 1] = 0
print(mask)

print(data.shape, mask.shape)

masked_data = mask[:, :, np.newaxis] * data
print(masked_data.shape)
print(masked_data[..., 2])

(3, 3, 10)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
(3, 3, 10) (3, 3)
(3, 3, 10)
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [33]:
data = np.ones((3, 3, 10))
print(data.shape)
print(data[..., -1])

mask = np.ones((3, 3, 1))
mask[1, 1] = 0
print(mask[..., -1])

print(data.shape, mask.shape)

masked_data = mask * data
print(masked_data.shape)
print(masked_data[..., 2])

(3, 3, 10)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
(3, 3, 10) (3, 3, 1)
(3, 3, 10)
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


###  Summary & Outlook

Most important basics about arrays:
- Know how to create arrays: `np.array()`, `np.arange()`, `np.ones()`, `np.zeros()`
- Feel good about dimensions with `array.shape`, know how to slice: `array[10:20:2, 10:20:2, -1]` and know how to handle the often times used `axis`-argument
- Obtain a subset of an array, especially via boolean masks: `a[a == 0] = 0`
- Know some operations (`array.mean()`, `array.max()`) and how to find them: `help()`, `np.lookfor()`, online docs, ...
- Broadcasting may be un-intuitive at first, but can feel very natural after a while, and it is extremely fast compared to loop-approaches (although more memory intensive)